---
services:
  www:
    depends_on:
      - db
    image: phpipam/phpipam-www:latest
    restart: always
    ports:
      - 8081:80
    environment:
      - TZ=Asia/Tokyo
      - IPAM_DATABASE_HOST=db
      - IPAM_DATABASE_USER=exampleuser
      - IPAM_DATABASE_PASS=examplepass
      - IPAM_DATABASE_NAME=exampledb
  db:
    image: mysql:8.4-oracle
    restart: always
    environment:
      - MYSQL_DATABASE=exampledb
      - MYSQL_USER=exampleuser
      - MYSQL_PASSWORD=examplepass
      - MYSQL_RANDOM_ROOT_PASSWORD='1'
networks:
 default:
  ipam:
   config:
    - subnet: 10.255.5.144/29
